### ISSUE TITLE
Latest upgrade of plex broke playback

### ISSUE THREAD

**Issue by FiremanKev** [salphonso/wmc2plex.bundle#6]
Upgraded to latest plex version and the channel does not work anymore

**Comment by salphonso** [comment]
Hey Kev,

I see you closed this.  did you get it all resolved?

**Comment by FiremanKev** [comment]
yes, it is working

**Comment by FiremanKev** [comment]
Yes, thank you for the app and keeping it up since WMC is dead by Microsoft. Great app
